### ISSUE TITLE
Sign up for FIRST Choice Round 2

### ISSUE THREAD

**Issue by frc6217** [FRC-6217/Code2018#13]

**Comment by josephtcoyle** [comment]
We have 210 Credits
Ideas
* 3 Power Cube Covers (10 credits each)
* 4 4inch Compliant Wheels for intake/conveyor (10 credits each)
* 1 Digital Mulimeter Fluke (100 credits) - do we have one already?

**Comment by josephtcoyle** [comment]
![capture](https://user-images.githubusercontent.com/18181177/34783683-cd5948ce-f5f1-11e7-82c6-72fc6a103b4d.JPG)
